#!/bin/bash

function _help() {
    echo "INCREMENATOR -- create the amount of necessary directories for each file with the specified extension."
    echo " "
    echo "incremenator -ext [extension] -dir [directory]"
    echo " "
    echo "Options:"
    echo "-h, --help                                   display this help page"
    echo "-d, -dir, --directory=DIRECTORY              the directory from which the files will be read"
    echo "-ex, -ext, --ext, --extension=EXTENSION      the extension the file must have in order to be counted"
}

function increment() {

  # Locally used variables (extension & directory)
  local EXT=""
  local DIR=""

  # Loop used for determining the values of the necessary flags, and which flags were supplied.
  for opt in "$@"; do
    case $opt in
      -h|--help|"")
          _help
          return
        ;;
      -ex|-ext|--ext|--extension)
          if [[ $2 = *"."* ]]; then
            echo "Please only include the extension's name without the dot (.)"
            return
          fi
          EXT="$2"
          shift 2
        ;;
      -d|-dir*|--directory)
          DIR="$2"
          shift 2
        ;;
    esac
  done

  if [ -z $EXT ] || [ -z $DIR ]; then
    _help
    return
  fi

  myfiles=()

  while IFS= read -r -d $'\0'; do
    myfiles+=($(basename $REPLY))
  done < <(find $DIR -type f -name "*.$EXT" -print0)

  g++ -std=c++17 save.cpp -o main.out 2>&1

  chmod +rw ./main.out

  ./main.out "${myfiles[@]}"
}
# Call increment function when script has been run
increment "$@"